name: ci
on: [push]

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      # only install dependencies using
      # https://github.com/cypress-io/github-action
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # will create the "dist" folder
      - name: Build site 🏗
        run: npm run build

      # only pass the local folder "dist"
      # TIP: we want to avoid uploading node_modules since it is SLOW
      # https://glebbahmutov.com/blog/parallel-cypress-tests-gh-action/
      - name: Save build folder 🆙
        uses: actions/upload-artifact@v2
        with:
          name: built
          path: |
            dist

  ui-tests:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Download the built folders ⏬
        uses: actions/download-artifact@v2
        with:
          name: built

      - run: ls -la
      - run: ls -la dist

      # reinstall dependencies and run Cypress tests
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # start the local server
          start: npm run serve
          wait-on: "http://localhost:5000"
          config: "baseUrl=http://localhost:5000"
